### ISSUE TITLE
There is no way to disable links 

### ISSUE THREAD

**Issue by xavierutox** [nagi1/hill-chart#14]
Hi,

I was using your library for one of my projects and have that following problem:

Even if no links are declared in the data parameters, it always falls back to "#" with no way to set it as null or straight up disable it

**Comment by nagi1** [comment]
Hey @xavierutox,

This happens because of this line here https://github.com/nagi1/hill-chart/blob/89f4c35cb70f73d6c089ef598eb9bbedc816aff0/src/index.js#L118,L133

I'm closing this because I would not consider it as an issue.
Please feel free to PR a replacement if you have the time.

Thanks.
