### ISSUE TITLE
Moved event behaves the same as 'move' event

### ISSUE THREAD

**Issue by andersfibiger** [nagi1/hill-chart#17]
It looks like 'moved' and 'move' events are fired at the same time, which means it cannot be used to set the state of the current datapoints.

I would think 'moved' would be triggered after you have released the mouse button again, so the new data points can be saved in a database.

**Comment by nagi1** [comment]
Hey Anders

Thanks for letting me know. 
I'll be working on it when I have some free time, in the meantime if you have done anything to fix this please feel free to open PR. 

Cheers

**Comment by andersfibiger** [comment]
Hey!

Perfect! I will take a look if I get time too :)
